const $ = id => document.getElementById(id);
const $$ = sel => [...document.querySelectorAll(sel)];
const sourceText=$("sourceText"),parseBtn=$("parseBtn"),clearBtn=$("clearBtn"),previewCard=$("previewCard"),duplicateBox=$("duplicateBox"),matchState=$("matchState"),confirmBtn=$("confirmBtn"),refreshBtn=$("refreshBtn"),toast=$("toast");
const fieldIds=["service_date","tour_type","representative","guests","nationality","phone","start_time","end_time","pickup_time","pickup_location","total_amount","currency","cash_collector_name","payment_status","notes"];
let duplicateBooking=null, scheduleData={today:"",tomorrow:"",results:[]}, me={actor:"",role:"partner"}, scheduleFilter="all";
function showToast(message){toast.textContent=message;toast.classList.remove("hidden");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.add("hidden"),2600)}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{"content-type":"application/json",...(options.headers||{})}});if(response.status===401){window.location.href="/fishing";throw new Error("Phiên đăng nhập đã hết hạn.")}const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}
function setBusy(button,busy,busyText="Đang xử lý..."){if(!button.dataset.label)button.dataset.label=button.textContent;button.disabled=busy;button.textContent=busy?busyText:button.dataset.label}
function esc(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function displayDate(iso){if(!iso)return"";const[y,m,d]=iso.split("-");return`${d}/${m}/${y}`}
function timeRange(row){if(row.start_time&&row.end_time)return`${row.start_time} - ${row.end_time}`;return row.start_time||row.pickup_time||"Chưa có giờ"}
function statusLabel(status){return({inquiry:"Mới",hold:"Giữ chỗ",confirmed:"Đã chốt",ready:"Sẵn sàng",running:"Đang chạy",completed:"Hoàn thành"})[status]||status||"-"}
function ready(row){return Boolean(row.driver_name&&row.boat_partner_name&&row.pickup_time)}
function goTab(name){$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));$$('.panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));window.scrollTo({top:0,behavior:'smooth'});if(name==='history')loadActivity()}
$$('.tab').forEach(btn=>btn.addEventListener('click',()=>goTab(btn.dataset.tab)));$$('[data-go]').forEach(btn=>btn.addEventListener('click',()=>goTab(btn.dataset.go)));
function fillPreview(result){for(const id of fieldIds){const node=$(id);if(node)node.value=result[id]??""}previewCard.classList.remove("hidden");previewCard.scrollIntoView({behavior:"smooth",block:"nearest"})}
function setDuplicate(duplicate){duplicateBooking=duplicate||null;if(!duplicate){duplicateBox.classList.add("hidden");duplicateBox.textContent="";matchState.textContent="Booking mới";$("confirmTitle").textContent="Kiểm tra lại trước khi lưu";$("confirmSubtitle").textContent="Có thể sửa trực tiếp các ô bên trên.";return}duplicateBox.classList.remove("hidden");duplicateBox.textContent=`Đã có booking ${duplicate.booking_code} cùng ngày cho ${duplicate.representative||duplicate.phone||"khách này"}. Xác nhận sẽ cập nhật booking hiện có, không tạo trùng.`;matchState.textContent="Sẽ cập nhật";$("confirmTitle").textContent="Đã tìm thấy booking hiện có";$("confirmSubtitle").textContent="Kiểm tra rồi xác nhận để cập nhật đúng dòng này."}
parseBtn.addEventListener("click",async()=>{const text=sourceText.value.trim();if(!text)return showToast("Dán nội dung booking trước.");setBusy(parseBtn,true,"Đang đọc...");try{const data=await api("/fishing/api/parse",{method:"POST",body:JSON.stringify({text})});fillPreview(data.result||{});setDuplicate(data.duplicate)}catch(e){showToast(e.message)}finally{setBusy(parseBtn,false)}});
clearBtn.addEventListener("click",()=>{sourceText.value="";duplicateBooking=null;previewCard.classList.add("hidden");sourceText.focus()});
confirmBtn.addEventListener("click",async()=>{const payload={};for(const id of fieldIds)payload[id]=$(id).value.trim();payload.guests=Number(payload.guests||0)||null;payload.total_amount=Number(payload.total_amount||0)||null;payload.source_text=sourceText.value.trim();if(duplicateBooking?.id)payload.booking_id=duplicateBooking.id;if(!payload.service_date)return showToast("Thiếu ngày tour.");if(!payload.representative&&!payload.phone)return showToast("Cần tên khách hoặc số điện thoại.");setBusy(confirmBtn,true,"Đang lưu...");try{const result=await api("/fishing/api/confirm",{method:"POST",body:JSON.stringify(payload)});showToast(result.action==="updated"?"Đã cập nhật booking.":"Đã thêm booking.");sourceText.value="";previewCard.classList.add("hidden");duplicateBooking=null;await loadSchedule();goTab('overview')}catch(e){showToast(e.message)}finally{setBusy(confirmBtn,false)}});
function tripCard(row){const driver=row.driver_name?`${esc(row.driver_name)}${row.vehicle_model?` · ${esc(row.vehicle_model)}`:""}${row.vehicle_plate?` · ${esc(row.vehicle_plate)}`:""}`:`<span class="missing">Chưa xếp tài xế</span>`;const boat=row.boat_partner_name?esc(row.boat_partner_name):`<span class="missing">Chưa xếp cano/tàu</span>`;const pickup=row.pickup_time||row.pickup_location?`${esc(row.pickup_time||"")}${row.pickup_time&&row.pickup_location?" · ":""}${esc(row.pickup_location||"")}`:`<span class="missing">Chưa có điểm đón</span>`;const returnDriver=row.return_driver_name?esc(row.return_driver_name):"Theo tài xế đi / cập nhật sau";const collectAmount=row.total_amount?`${Number(row.total_amount).toLocaleString("vi-VN")} ${esc(row.currency||"VND")}`:"Chưa có giá thu";const collector=row.cash_collector_name?esc(row.cash_collector_name):"Chưa chỉ định";const isReady=ready(row);return`<article class="trip-card"><div class="trip-main"><div class="trip-date"><strong>${esc(displayDate(row.service_date))} · ${esc(timeRange(row))}</strong><span class="pill ${isReady?"ready":"warn"}">${isReady?"Đủ vận hành":"Cần bổ sung"}</span><span class="pill">${esc(statusLabel(row.status))}</span></div><div class="guest">${esc(row.representative||"Khách chưa đặt tên")} · ${esc(row.guest_label||row.guests||"?")} khách</div><div class="meta">${esc(row.nationality||"Chưa rõ quốc tịch")} · ${esc(row.tour_type||"Big Fishing")}${row.phone?` · ${esc(row.phone)}`:""}</div><div class="owner-line">Nhập bởi: ${esc(row.owner_name||"JoTrip")}</div></div><div class="ops"><div class="ops-line"><span>Đón khách</span><span>${pickup}</span></div><div class="ops-line"><span>Thu tiền</span><span>${collectAmount} · ${collector}</span></div><div class="ops-line"><span>Tài xế đi</span><span>${driver}</span></div><div class="ops-line"><span>Cano / tàu</span><span>${boat}</span></div><div class="ops-line"><span>Tài xế về</span><span>${returnDriver}</span></div></div></article>`}
function renderList(target,rows,emptyText){target.innerHTML=rows.length?rows.map(tripCard).join(""):`<div class="empty">${esc(emptyText)}</div>`}
function datePlus(iso,days){const d=new Date(`${iso}T00:00:00+07:00`);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function filteredRows(){const rows=scheduleData.results||[];if(scheduleFilter==='today')return rows.filter(x=>x.service_date===scheduleData.today);if(scheduleFilter==='tomorrow')return rows.filter(x=>x.service_date===scheduleData.tomorrow);if(scheduleFilter==='week'){const end=datePlus(scheduleData.today,7);return rows.filter(x=>x.service_date>=scheduleData.today&&x.service_date<end)}if(scheduleFilter==='mine')return rows.filter(x=>(x.owner_name||'').toLowerCase()===(me.actor||'').toLowerCase()||(x.boat_partner_name||'').toLowerCase().includes((me.actor||'').toLowerCase()));return rows}
function renderSchedule(){const rows=scheduleData.results||[];const today=rows.filter(x=>x.service_date===scheduleData.today),tomorrow=rows.filter(x=>x.service_date===scheduleData.tomorrow),end=datePlus(scheduleData.today,7),week=rows.filter(x=>x.service_date>=scheduleData.today&&x.service_date<end),missing=rows.filter(x=>x.service_date>=scheduleData.today&&!ready(x));$("kpiToday").textContent=today.length;$("kpiTomorrow").textContent=tomorrow.length;$("kpiMissing").textContent=missing.length;$("kpiWeek").textContent=week.length;renderList($("overviewTrips"),rows.filter(x=>x.service_date>=scheduleData.today).slice(0,5),"Chưa có tour sắp tới.");renderList($("scheduleAll"),filteredRows(),"Không có tour trong bộ lọc này.");$("lastUpdated").textContent=`Cập nhật ${new Date().toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"})}`;renderOps()}
function renderOps(){const rows=(scheduleData.results||[]).filter(x=>x.service_date>=scheduleData.today).sort((a,b)=>Number(ready(a))-Number(ready(b))||a.service_date.localeCompare(b.service_date));$("opsBoard").innerHTML=rows.length?rows.map(r=>`<article class="ops-row"><div class="ops-date">${esc(displayDate(r.service_date))}<br><span class="pill ${ready(r)?'ready':'warn'}">${ready(r)?'Đủ':'Thiếu'}</span></div><div class="ops-guest">${esc(r.representative||'Khách')} · ${esc(r.guests||'?')} khách<br><span class="meta">${esc(timeRange(r))}</span></div><div class="ops-cell"><b>Tài xế</b>${r.driver_name?esc(r.driver_name):'<span class="missing">Chưa xếp</span>'}</div><div class="ops-cell"><b>Cano / tàu</b>${r.boat_partner_name?esc(r.boat_partner_name):'<span class="missing">Chưa xếp</span>'}</div><div class="ops-cell"><b>Đón</b>${r.pickup_time||r.pickup_location?esc(`${r.pickup_time||''}${r.pickup_time&&r.pickup_location?' · ':''}${r.pickup_location||''}`):'<span class="missing">Chưa có</span>'}</div></article>`).join(''):'<div class="empty">Chưa có tour cần điều phối.</div>'}
$$('#scheduleFilters .filter').forEach(btn=>btn.addEventListener('click',()=>{scheduleFilter=btn.dataset.filter;$$('#scheduleFilters .filter').forEach(x=>x.classList.toggle('active',x===btn));renderSchedule()}));
async function loadSchedule(){try{scheduleData=await api("/fishing/api/schedule");renderSchedule()}catch(e){$("overviewTrips").innerHTML=`<div class="empty">Không tải được lịch: ${esc(e.message)}</div>`;$("scheduleAll").innerHTML=$("overviewTrips").innerHTML;$("opsBoard").innerHTML=$("overviewTrips").innerHTML}}
async function loadActivity(){try{const data=await api('/fishing/api/activity');const rows=data.results||[];$("activityList").innerHTML=rows.length?rows.map(r=>`<article class="timeline-item"><div class="timeline-time">${esc(new Date((r.created_at||'').replace(' ','T')+'Z').toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}))}</div><div class="timeline-main"><strong>${esc(r.actor_name)} · ${esc(r.action==='created'?'Thêm tour':r.action==='updated'?'Cập nhật':'Hoạt động')}</strong><span>${esc(r.summary)}</span></div></article>`).join(''):'<div class="empty">Chưa có lịch sử.</div>'}catch(e){$("activityList").innerHTML=`<div class="empty">Không tải được lịch sử: ${esc(e.message)}</div>`}}
async function bootstrap(){try{me=await api('/fishing/api/me');$("userPill").textContent=me.company||me.actor}catch{}await loadSchedule()}
refreshBtn.addEventListener('click',async()=>{setBusy(refreshBtn,true,'…');await Promise.all([loadSchedule(),loadActivity()]);setBusy(refreshBtn,false)});
bootstrap();
